### ISSUE TITLE
predict should return conditional probabilities

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#28]
think about the returned probabilities. They are the joint, maybe the user prefer the conditional one, in order also to sum up to 1.

**Comment by FedericoCarli** [comment]
https://github.com/gherardovarando/stagedtrees/blob/9316952b1b2ec1573622bf9f42236ff0ca97a87e/R/3-inference-functions.R#L55-L57

is it okay to transpose x? x is for example an expand.grid object, rows and columns are already rows and columns

**Comment by gherardovarando** [comment]
`x <- as.data.frame(t(x))`  is executed only if `dim(x)` is `NULL` so `x` in that case can not be a `data.frame`. If `is.null(dim(x))` then `x` is assumed to be a named vector like `c(A = "yes", B = "high")`.

**Comment by gherardovarando** [comment]
```
mod <- full(PhDArticles, lambda = 1)
prob.sevt(mod, c(Gender = "male", Prestige = "low" ))
```
