### ISSUE TITLE
join_stages with non-existing stages

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#37]
w1 <- staged_ev_tree(chds, full = FALSE, fit = TRUE) 
w1$stages
join_stages(w1, "Admission", "1", "2")

**Error in log(sevt$prob[[v]][[s2]]) : 
  non-numeric argument to mathematical function**

Because there is only stage "1" for level "Admission". 
We can for example put a _warning message_ : "Admission is marginally independent from the previous variables, so all situations are already merged together."

**Comment by gherardovarando** [comment]
```
data("Titanic")
w1 <- staged_ev_tree(Titanic, full = FALSE, fit = TRUE)
join_stages(w1, "Sex", "1", "2")  #should return w1 unchanged
```

**Comment by gherardovarando** [comment]
Now `join_stages` throws a specific error if trying to join non-existing stages.
