### ISSUE TITLE
Joining stages with 0 observations (lambda = 0) 

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#39]
m1 <- full(Trump, fit = TRUE)
m2 <- bhc.sevt(m1)

**Error in if (try_score >= temp_score) { : 
  valore mancante dove è richiesto TRUE/FALSE**

with m1 <- full(Trump, fit = TRUE, **lambda = 1**) it works. 
Maybe fix as default lambda = 1 in full function.

**Comment by gherardovarando** [comment]
- I vote against default `lambda = 1` in `full()`

**Comment by gherardovarando** [comment]
@FedericoCarli could you find where the actual problem is ?  I probably think it is in `join_stages` and probably in the line the logLik is updated https://github.com/gherardovarando/stagedtrees/blob/d09bb4868a598f1472374b432293b6d314fcfa79/R/1b-base-model-function.R#L355
