### ISSUE TITLE
predict of expand.grid(...)

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#61]
mod0 <- full(PhDArticles[, 1:3], lambda = 0)
p0 <- predict(mod0, newdata = expand.grid(mod0$tree[1:3]), class = "Kids", prob = T)
p0
sum(rowSums(p0))  # if Kids had had 4 categories, p0 would sum to 4.

mod0$ctables$Kids / NROW(PhDArticles) # here we have the "real expand grid", the real joint distribution that sums to 1. 

sum(mod0$ctables$Kids / NROW(PhDArticles))

**Comment by FedericoCarli** [comment]
Opened to have a feedback from you. 

In the afternoon I will send a pull request with the implementation of the conditional.predict, in order to sum up to 1 the distribution of each situation. I have to do some checks and tests before upload it!

**Comment by gherardovarando** [comment]
what we would like is the conditional probabilities, now the joint probabilities are returned. 
We do not want that they sum up to one when summing on different predictors variables

**Comment by gherardovarando** [comment]
This has problems and should work

```
p0 <- predict(mod0, newdata = expand.grid(mod0$tree[1:2]), class = "Kids", prob = T)
```

**Comment by FedericoCarli** [comment]
exactly, this is the command we want to use in order to predict the third variable

**Comment by gherardovarando** [comment]
I opened issue #62, feel free to fix it. 
it is easily fixed  adding the class variable (with `NA` values, but with appropriate levels) to the `newdata`.
