### ISSUE TITLE
naive.sevt bug 

### ISSUE THREAD

**Issue by FedericoCarli** [gherardovarando/stagedtrees#70]
naive.sevt does not work if the full model is estimated with lambda = 0 (and we have NaN in $prob).

# does not work
foo <- full(PhDArticles, lambda = 0)
foo <- naive.sevt(foo)

# does work
foo <- full(PhDArticles, lambda = 0.00001)
foo <- naive.sevt(foo)

a solution can be to force to be 0 the distance between 2 NaN distributions. We have to think how to treat a distance between a NaN distribution and a not-degenerate distribution. (NaN can be interpreted as 0 probability for each level?)

**Comment by gherardovarando** [comment]
I think the solution is to use a distance that will not output NaN for degenerate distributions, e.g. `lp`. 
Currently this is not working because of issue #73 .
